In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('student-mat.csv', sep=';')

FileNotFoundError: [Errno 2] No such file or directory: 'student_prediction.csv'

In [3]:
df = pd.read_csv('student-mat.csv')

In [4]:
df.head

<bound method NDFrame.head of     school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0    GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1    GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2    GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3    GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4    GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...
..                                                 ...
390  MS;"M";20;"U";"LE3";"A";2;2;"services";"servic...
391  MS;"M";17;"U";"LE3";"T";3;1;"services";"servic...
392  MS;"M";21;"R";"GT3";"T";1;1;"other";"other";"c...
393  MS;"M";18;"R";"LE3";"T";3;2;"services";"other"...
394  MS;"M";19;"U";"LE3";"T";1;1;"other";"at_home";...

[395 rows x 1 columns]>

In [5]:
df.shape

(395, 1)

In [7]:
df = pd.read_csv("student-mat.csv", sep=";")

In [8]:
df.shape

(395, 33)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [10]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [11]:
df=df.drop(columns=['G1','G2'])

In [12]:
df.shape

(395, 31)

In [13]:
df.select_dtypes(include='object').columns

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [14]:
df = pd.get_dummies(df)

In [15]:
df.shape

(395, 57)

In [16]:
df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,activities_no,activities_yes,nursery_no,nursery_yes,higher_no,higher_yes,internet_no,internet_yes,romantic_no,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,True,False,False,True,False,True,True,False,True,False
1,17,1,1,1,2,0,5,3,3,1,...,True,False,True,False,False,True,False,True,True,False
2,15,1,1,1,2,3,4,3,2,2,...,True,False,False,True,False,True,False,True,True,False
3,15,4,2,1,3,0,3,2,2,1,...,False,True,False,True,False,True,False,True,False,True
4,16,3,3,1,2,0,4,3,2,1,...,True,False,False,True,False,True,True,False,True,False

In [17]:
x = df.drop(columns=['G3'])

In [18]:
y=df

In [19]:
y = df['G3']

In [20]:
print(x.shape)

(395, 56)

In [21]:
print(y.shape)

(395,)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [24]:
print(X_train.shape)

(316, 56)

In [25]:
print(X_test.shape)

NameError: name 'x_test' is not defined

In [26]:
print(X_test.shape)

(79, 56)

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [28]:
model = RandomForestRegressor(random_state=42)

In [29]:
model.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [30]:
model.predict(X_test)

array([13.23,  8.56, 10.16, 12.05, 10.93,  8.71, 11.27,  7.2 ,  8.98,
        8.61, 10.92, 10.48, 11.07, 10.81, 13.15, 13.21, 12.36, 13.45,
       13.67,  9.08, 11.69, 12.02, 10.53,  9.87, 13.49, 12.87, 12.99,
        3.01, 11.52, 11.41, 11.8 ,  7.79, 11.  , 10.37,  9.69, 10.31,
        5.69,  9.19, 12.81, 12.06,  8.26, 12.42, 10.83, 13.29,  9.18,
        9.39, 11.73,  7.62,  9.29,  5.62,  1.84, 12.19, 10.75,  6.01,
        3.06, 11.45, 10.01,  3.97, 11.41, 12.7 , 12.14,  8.95, 12.6 ,
       12.17,  4.  , 12.58, 10.3 , 10.87, 10.26,  8.21, 13.06,  8.  ,
        8.79, 12.33, 11.28, 13.06, 10.71, 11.99, 11.49])

In [31]:
df.X_test = predictions

NameError: name 'predictions' is not defined

In [32]:
predictions = model.predict(X_test)

In [33]:
print(predictions)

[13.23  8.56 10.16 12.05 10.93  8.71 11.27  7.2   8.98  8.61 10.92 10.48
 11.07 10.81 13.15 13.21 12.36 13.45 13.67  9.08 11.69 12.02 10.53  9.87
 13.49 12.87 12.99  3.01 11.52 11.41 11.8   7.79 11.   10.37  9.69 10.31
  5.69  9.19 12.81 12.06  8.26 12.42 10.83 13.29  9.18  9.39 11.73  7.62
  9.29  5.62  1.84 12.19 10.75  6.01  3.06 11.45 10.01  3.97 11.41 12.7
 12.14  8.95 12.6  12.17  4.   12.58 10.3  10.87 10.26  8.21 13.06  8.
  8.79 12.33 11.28 13.06 10.71 11.99 11.49]

In [ ]:
from sklearn.metrics import mean_absolute_error

ImportError: cannot import name 'mean_absolute_error' from 'sklearn.model_selection' (/opt/anaconda3/lib/python3.13/site-packages/sklearn/model_selection/__init__.py)

In [35]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predictions)
print(mae)

2.7182278481012654

In [36]:
df.head

<bound method NDFrame.head of      age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  \
0     18     4     4           2          2         0       4         3
1     17     1     1           1          2         0       5         3
2     15     1     1           1          2         3       4         3
3     15     4     2           1          3         0       3         2
4     16     3     3           1          2         0       4         3
..   ...   ...   ...         ...        ...       ...     ...       ...
390   20     2     2           1          2         2       5         5
391   17     3     1           2          1         0       2         4
392   21     1     1           1          1         3       5         5
393   18     3     2           3          1         0       4         4
394   19     1     1           1          1         0       3         2

     goout  Dalc  ...  activities_no  activities_yes  nursery_no  nursery_yes  \
0        4     1  ...           True           False       False         True
1        3     1  ...           True           False        True        False
2        2     2  ...           True           False       False         True
3        2     1  ...          False            True       False         True
4        2     1  ...           True           False       False         True
..     ...   ...  ...            ...             ...         ...          ...
390      4     4  ...           True           False       False         True
391      5     3  ...           True           False        True        False
392      3     3  ...           True           False        True        False
393      1     3  ...           True           False        True        False
394      3     3  ...           True           False       False         True

     higher_no  higher_yes  internet_no  internet_yes  romantic_no  \
0        False        True         True         False         True
1        False        True        False          True         True
2        False        True        False          True         True
3        False        True        False          True        False
4        False        True         True         False         True
..         ...         ...          ...           ...          ...
390      False        True         True         False         True
391      False        True        False          True         True
392      False        True         True         False         True
393      False        True        False          True         True
394      False        True        False          True         True

     romantic_yes
0           False
1           False
2           False
3            True
4           False
..            ...
390         False
391         False
392         False
393         False
394         False

[395 rows x 57 columns]>